name : Test

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        pipenv install coveralls --skip-lock

    - name: Test with pytest
      run: |
        pipenv run pytest --cov=app
        
    - name: Coveralls
      if: ${{ always() }}
      run: pipenv run coveralls
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}